name: HomesPE
version: 1.0.0-alpha2
author: Terpz710
api: [5.0.0]
main: Terpz710\HomesPE\Main
description: Simple homes system

permissions:
  homespe.sethome:
    description: Allows players to set their home.
    default: true
  homespe.home:
    description: Allows players to teleport to their home.
    default: true
  homespe.delhome:
    description: Allows players to delete their home.
    default: true
  homespe.homes:
    description: Allows players to list their available home locations.
    default: true
